try to fix configure for gtkextra

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7439,7 +7439,7 @@ fi;
      fi
   fi
 
-  # Extract the first word of "gtkextra-config", so it can be a program name with args.
+ # Extract the first word of "gtkextra-config", so it can be a program name with args.
 set dummy gtkextra-config; ac_word=$2
 echo "$as_me:7444: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
@@ -7485,10 +7485,14 @@ echo $ECHO_N "checking for GTKEXTRA - version >= $min_gtkextra_version... $ECHO_
     no_gtkextra=yes
     echo "$as_me:7486: result: no" >&5
 echo "${ECHO_T}no" >&6
-    echo
-    echo "* You need the gtkextra library to compile gretl."
-    echo "* You can get this from gtkextra.sourceforge.net.
-    exit
+    if test -d gui/gtkextra ; then
+       echo "* Will try using the gretl gtkextra addon package instead"
+    else
+       echo
+       echo "* You need the gtkextra library to compile gretl."
+       echo "* You can get this from gtkextra.sourceforge.net"
+       exit
+    fi
   else
     have_gtkextra=yes
     # AC_MSG_RESULT(yes)
@@ -7511,7 +7515,7 @@ echo "${ECHO_T}no" >&6
   echo $ac_n "cross compiling; assumed OK... $ac_c"
 else
   cat >conftest.$ac_ext <<_ACEOF
-#line 7514 "configure"
+#line 7518 "configure"
 #include "confdefs.h"
 
 #include <gtkextra/gtkextra.h>
@@ -7569,17 +7573,17 @@ main ()
 
 _ACEOF
 rm -f conftest$ac_exeext
-if { (eval echo "$as_me:7572: \"$ac_link\"") >&5
+if { (eval echo "$as_me:7576: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:7575: \$? = $ac_status" >&5
+  echo "$as_me:7579: \$? = $ac_status" >&5
   (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
-  { (eval echo "$as_me:7577: \"$ac_try\"") >&5
+  { (eval echo "$as_me:7581: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:7580: \$? = $ac_status" >&5
+  echo "$as_me:7584: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  echo "$as_me:7582: result: yes" >&5
+  echo "$as_me:7586: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 else
   echo "$as_me: program exited with status $ac_status" >&5
@@ -7594,6 +7598,10 @@ fi
   fi
 
 # end of "build_gui" conditionality
+fi
+
+if test "${have_gtkextra}" = "no" ; then
+   exit
 fi
 
 if test "${prefix}" = "NONE" ; then
@@ -7683,7 +7691,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:7686: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:7694: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -7856,7 +7864,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:7859: error: ambiguous option: $1
+    { { echo "$as_me:7867: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -7875,7 +7883,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:7878: error: unrecognized option: $1
+  -*) { { echo "$as_me:7886: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -7914,7 +7922,7 @@ do
   "gretl_sh" ) CONFIG_FILES="$CONFIG_FILES gretl_sh" ;;
   "gretl-config" ) CONFIG_FILES="$CONFIG_FILES gretl-config" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:7917: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:7925: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -8156,7 +8164,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:8159: creating $ac_file" >&5
+    { echo "$as_me:8167: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -8174,7 +8182,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:8177: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:8185: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -8187,7 +8195,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:8190: error: cannot find input file: $f" >&5
+           { { echo "$as_me:8198: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -8248,7 +8256,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:8251: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:8259: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -8259,7 +8267,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:8262: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:8270: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -8272,7 +8280,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:8275: error: cannot find input file: $f" >&5
+           { { echo "$as_me:8283: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -8389,7 +8397,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:8392: $ac_file is unchanged" >&5
+      { echo "$as_me:8400: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
