remove more old cruft

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -906,9 +906,6 @@ GDK_PIXBUF_CFLAGS
 GDK_PIXBUF_LIBS
 GNOME_CFLAGS
 GNOME_LIBS
-GCONFTOOL
-GCONF_SCHEMA_CONFIG_SOURCE
-GCONF_SCHEMA_FILE_DIR
 have_gnome
 gnome_prefix
 XMLCONF
@@ -1561,8 +1558,6 @@ Optional Packages:
   --with-mpfr-prefix=PFX   Prefix where MPFR is installed (optional)
   --with-lapack-prefix=PFX   Prefix where LAPACK is installed (optional)
   --with-flite-prefix=PFX   Prefix where FLITE is installed (optional)
-  --with-gconf-source=sourceaddress      Config database for installing schema files.
-  --with-gconf-schema-file-dir=dir        Directory for installing schema files.
 
 Some influential environment variables:
   CC          C compiler command
@@ -7213,7 +7208,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 7216 "configure"' > conftest.$ac_ext
+  echo '#line 7211 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9331,11 +9326,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9334: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9329: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9338: \$? = $ac_status" >&5
+   echo "$as_me:9333: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -9574,11 +9569,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9577: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9572: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9581: \$? = $ac_status" >&5
+   echo "$as_me:9576: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -9634,11 +9629,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9637: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9632: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9641: \$? = $ac_status" >&5
+   echo "$as_me:9636: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11782,7 +11777,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11785 "configure"
+#line 11780 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11880,7 +11875,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11883 "configure"
+#line 11878 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14069,11 +14064,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14072: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14067: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14076: \$? = $ac_status" >&5
+   echo "$as_me:14071: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -14129,11 +14124,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14132: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14127: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14136: \$? = $ac_status" >&5
+   echo "$as_me:14131: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15457,7 +15452,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 15460 "configure"
+#line 15455 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -15555,7 +15550,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 15558 "configure"
+#line 15553 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -16392,11 +16387,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16395: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16390: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16399: \$? = $ac_status" >&5
+   echo "$as_me:16394: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -16452,11 +16447,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16455: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16450: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16459: \$? = $ac_status" >&5
+   echo "$as_me:16454: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18482,11 +18477,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18485: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18480: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18489: \$? = $ac_status" >&5
+   echo "$as_me:18484: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -18725,11 +18720,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18728: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18723: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18732: \$? = $ac_status" >&5
+   echo "$as_me:18727: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -18785,11 +18780,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18788: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18783: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18792: \$? = $ac_status" >&5
+   echo "$as_me:18787: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20933,7 +20928,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 20936 "configure"
+#line 20931 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -21031,7 +21026,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 21034 "configure"
+#line 21029 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -26541,12 +26536,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_GNOME_CFLAGS="$GNOME_CFLAGS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libgnomeui-2.0 libgnomeprint-2.2 libgnomeprintui-2.2 gconf-2.0\"") >&5
-  ($PKG_CONFIG --exists --print-errors "libgnomeui-2.0 libgnomeprint-2.2 libgnomeprintui-2.2 gconf-2.0") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libgnomeui-2.0 libgnomeprint-2.2 libgnomeprintui-2.2\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libgnomeui-2.0 libgnomeprint-2.2 libgnomeprintui-2.2") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GNOME_CFLAGS=`$PKG_CONFIG --cflags "libgnomeui-2.0 libgnomeprint-2.2 libgnomeprintui-2.2 gconf-2.0" 2>/dev/null`
+  pkg_cv_GNOME_CFLAGS=`$PKG_CONFIG --cflags "libgnomeui-2.0 libgnomeprint-2.2 libgnomeprintui-2.2" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -26559,12 +26554,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_GNOME_LIBS="$GNOME_LIBS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libgnomeui-2.0 libgnomeprint-2.2 libgnomeprintui-2.2 gconf-2.0\"") >&5
-  ($PKG_CONFIG --exists --print-errors "libgnomeui-2.0 libgnomeprint-2.2 libgnomeprintui-2.2 gconf-2.0") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libgnomeui-2.0 libgnomeprint-2.2 libgnomeprintui-2.2\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libgnomeui-2.0 libgnomeprint-2.2 libgnomeprintui-2.2") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GNOME_LIBS=`$PKG_CONFIG --libs "libgnomeui-2.0 libgnomeprint-2.2 libgnomeprintui-2.2 gconf-2.0" 2>/dev/null`
+  pkg_cv_GNOME_LIBS=`$PKG_CONFIG --libs "libgnomeui-2.0 libgnomeprint-2.2 libgnomeprintui-2.2" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -26583,9 +26578,9 @@ else
         _pkg_short_errors_supported=no
 fi
         if test $_pkg_short_errors_supported = yes; then
-	        GNOME_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "libgnomeui-2.0 libgnomeprint-2.2 libgnomeprintui-2.2 gconf-2.0"`
+	        GNOME_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "libgnomeui-2.0 libgnomeprint-2.2 libgnomeprintui-2.2"`
         else
-	        GNOME_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libgnomeui-2.0 libgnomeprint-2.2 libgnomeprintui-2.2 gconf-2.0"`
+	        GNOME_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libgnomeui-2.0 libgnomeprint-2.2 libgnomeprintui-2.2"`
         fi
 	# Put the nasty error message in config.log where it belongs
 	echo "$GNOME_PKG_ERRORS" >&5
@@ -26622,12 +26617,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_GNOME_CFLAGS="$GNOME_CFLAGS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libgnomeui-2.0 gconf-2.0\"") >&5
-  ($PKG_CONFIG --exists --print-errors "libgnomeui-2.0 gconf-2.0") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libgnomeui-2.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libgnomeui-2.0") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GNOME_CFLAGS=`$PKG_CONFIG --cflags "libgnomeui-2.0 gconf-2.0" 2>/dev/null`
+  pkg_cv_GNOME_CFLAGS=`$PKG_CONFIG --cflags "libgnomeui-2.0" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -26640,12 +26635,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_GNOME_LIBS="$GNOME_LIBS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libgnomeui-2.0 gconf-2.0\"") >&5
-  ($PKG_CONFIG --exists --print-errors "libgnomeui-2.0 gconf-2.0") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libgnomeui-2.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libgnomeui-2.0") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_GNOME_LIBS=`$PKG_CONFIG --libs "libgnomeui-2.0 gconf-2.0" 2>/dev/null`
+  pkg_cv_GNOME_LIBS=`$PKG_CONFIG --libs "libgnomeui-2.0" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -26664,9 +26659,9 @@ else
         _pkg_short_errors_supported=no
 fi
         if test $_pkg_short_errors_supported = yes; then
-	        GNOME_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "libgnomeui-2.0 gconf-2.0"`
+	        GNOME_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "libgnomeui-2.0"`
         else
-	        GNOME_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libgnomeui-2.0 gconf-2.0"`
+	        GNOME_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libgnomeui-2.0"`
         fi
 	# Put the nasty error message in config.log where it belongs
 	echo "$GNOME_PKG_ERRORS" >&5
@@ -26805,85 +26800,6 @@ else
 echo "${ECHO_T}yes" >&6; }
 	:
 fi
-	 # Extract the first word of "gconftool-2", so it can be a program name with args.
-set dummy gconftool-2; ac_word=$2
-{ echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_GCONFTOOL+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $GCONFTOOL in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_GCONFTOOL="$GCONFTOOL" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_GCONFTOOL="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-IFS=$as_save_IFS
-
-  test -z "$ac_cv_path_GCONFTOOL" && ac_cv_path_GCONFTOOL="no"
-  ;;
-esac
-fi
-GCONFTOOL=$ac_cv_path_GCONFTOOL
-if test -n "$GCONFTOOL"; then
-  { echo "$as_me:$LINENO: result: $GCONFTOOL" >&5
-echo "${ECHO_T}$GCONFTOOL" >&6; }
-else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
-
-
-	 if test x"$GCONFTOOL" = xno; then
-            { { echo "$as_me:$LINENO: error: gconftool-2 executable not found in your path" >&5
-echo "$as_me: error: gconftool-2 executable not found in your path" >&2;}
-   { (exit 1); exit 1; }; }
-         else
-
-  GCONF_SCHEMA_CONFIG_SOURCE=`gconftool-2 --get-default-source`
-
-
-# Check whether --with-gconf-source was given.
-if test "${with_gconf_source+set}" = set; then
-  withval=$with_gconf_source; GCONF_SCHEMA_CONFIG_SOURCE="$withval"
-fi
-
-
-
-  { echo "$as_me:$LINENO: result: Using config source $GCONF_SCHEMA_CONFIG_SOURCE for schema installation" >&5
-echo "${ECHO_T}Using config source $GCONF_SCHEMA_CONFIG_SOURCE for schema installation" >&6; }
-
-  if test "x$GCONF_SCHEMA_FILE_DIR" = "x"; then
-    GCONF_SCHEMA_FILE_DIR='$(sysconfdir)/gconf/schemas/'
-  else
-    GCONF_SCHEMA_FILE_DIR=$GCONF_SCHEMA_FILE_DIR
-  fi
-
-
-# Check whether --with-gconf-schema-file-dir was given.
-if test "${with_gconf_schema_file_dir+set}" = set; then
-  withval=$with_gconf_schema_file_dir; GCONF_SCHEMA_FILE_DIR="$withval"
-fi
-
-
-
-  { echo "$as_me:$LINENO: result: Using $GCONF_SCHEMA_FILE_DIR as install directory for schema files" >&5
-echo "${ECHO_T}Using $GCONF_SCHEMA_FILE_DIR as install directory for schema files" >&6; }
-
-
-         fi
     fi
 
 
@@ -27154,7 +27070,7 @@ _ACEOF
 
 
 CFLAGS="$orig_CFLAGS"
-ac_config_files="$ac_config_files Makefile gretl_sh gretl-config gretl.pc gui2/Makefile gui2/debug gui2/gtkextra-lite/Makefile gui2/gtksourceview/Makefile gui2/omf-install/Makefile gnome/Makefile gnome/gretl.keys cli/Makefile cli/debug lib/Makefile plugin/Makefile po/Makefile.in share/Makefile share/bcih/Makefile tests/Makefile extra/Makefile redhat/gretl.spec"
+ac_config_files="$ac_config_files Makefile gretl_sh gretl-config gretl.pc gui2/Makefile gui2/debug gui2/gtkextra-lite/Makefile gui2/gtksourceview/Makefile gnome/Makefile gnome/gretl.keys cli/Makefile cli/debug lib/Makefile plugin/Makefile po/Makefile.in share/Makefile share/bcih/Makefile tests/Makefile extra/Makefile redhat/gretl.spec"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -27734,7 +27650,6 @@ do
     "gui2/debug") CONFIG_FILES="$CONFIG_FILES gui2/debug" ;;
     "gui2/gtkextra-lite/Makefile") CONFIG_FILES="$CONFIG_FILES gui2/gtkextra-lite/Makefile" ;;
     "gui2/gtksourceview/Makefile") CONFIG_FILES="$CONFIG_FILES gui2/gtksourceview/Makefile" ;;
-    "gui2/omf-install/Makefile") CONFIG_FILES="$CONFIG_FILES gui2/omf-install/Makefile" ;;
     "gnome/Makefile") CONFIG_FILES="$CONFIG_FILES gnome/Makefile" ;;
     "gnome/gretl.keys") CONFIG_FILES="$CONFIG_FILES gnome/gretl.keys" ;;
     "cli/Makefile") CONFIG_FILES="$CONFIG_FILES cli/Makefile" ;;
@@ -27989,9 +27904,6 @@ GDK_PIXBUF_CFLAGS!$GDK_PIXBUF_CFLAGS$ac_delim
 GDK_PIXBUF_LIBS!$GDK_PIXBUF_LIBS$ac_delim
 GNOME_CFLAGS!$GNOME_CFLAGS$ac_delim
 GNOME_LIBS!$GNOME_LIBS$ac_delim
-GCONFTOOL!$GCONFTOOL$ac_delim
-GCONF_SCHEMA_CONFIG_SOURCE!$GCONF_SCHEMA_CONFIG_SOURCE$ac_delim
-GCONF_SCHEMA_FILE_DIR!$GCONF_SCHEMA_FILE_DIR$ac_delim
 have_gnome!$have_gnome$ac_delim
 gnome_prefix!$gnome_prefix$ac_delim
 XMLCONF!$XMLCONF$ac_delim
@@ -28002,7 +27914,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 53; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 50; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -29128,7 +29040,6 @@ do
     "gui2/debug") CONFIG_FILES="$CONFIG_FILES gui2/debug" ;;
     "gui2/gtkextra-lite/Makefile") CONFIG_FILES="$CONFIG_FILES gui2/gtkextra-lite/Makefile" ;;
     "gui2/gtksourceview/Makefile") CONFIG_FILES="$CONFIG_FILES gui2/gtksourceview/Makefile" ;;
-    "gui2/omf-install/Makefile") CONFIG_FILES="$CONFIG_FILES gui2/omf-install/Makefile" ;;
     "gnome/Makefile") CONFIG_FILES="$CONFIG_FILES gnome/Makefile" ;;
     "gnome/gretl.keys") CONFIG_FILES="$CONFIG_FILES gnome/gretl.keys" ;;
     "cli/Makefile") CONFIG_FILES="$CONFIG_FILES cli/Makefile" ;;
@@ -29388,9 +29299,6 @@ GDK_PIXBUF_CFLAGS!$GDK_PIXBUF_CFLAGS$ac_delim
 GDK_PIXBUF_LIBS!$GDK_PIXBUF_LIBS$ac_delim
 GNOME_CFLAGS!$GNOME_CFLAGS$ac_delim
 GNOME_LIBS!$GNOME_LIBS$ac_delim
-GCONFTOOL!$GCONFTOOL$ac_delim
-GCONF_SCHEMA_CONFIG_SOURCE!$GCONF_SCHEMA_CONFIG_SOURCE$ac_delim
-GCONF_SCHEMA_FILE_DIR!$GCONF_SCHEMA_FILE_DIR$ac_delim
 have_gnome!$have_gnome$ac_delim
 gnome_prefix!$gnome_prefix$ac_delim
 XMLCONF!$XMLCONF$ac_delim
@@ -29401,7 +29309,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 53; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 50; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
