add conditionality on glib-2.0 >= 2.28.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -681,6 +681,9 @@ GTK2_LIBS
 GTK2_CFLAGS
 JSON_GLIB_LIBS
 JSON_GLIB_CFLAGS
+RT_LIB
+GLIB28_LIBS
+GLIB28_CFLAGS
 GLIB_LIBS
 GLIB_CFLAGS
 CURL_LIBS
@@ -904,6 +907,8 @@ CURL_CFLAGS
 CURL_LIBS
 GLIB_CFLAGS
 GLIB_LIBS
+GLIB28_CFLAGS
+GLIB28_LIBS
 JSON_GLIB_CFLAGS
 JSON_GLIB_LIBS
 GTK2_CFLAGS
@@ -1618,6 +1623,9 @@ Some influential environment variables:
   CURL_LIBS   linker flags for CURL, overriding pkg-config
   GLIB_CFLAGS C compiler flags for GLIB, overriding pkg-config
   GLIB_LIBS   linker flags for GLIB, overriding pkg-config
+  GLIB28_CFLAGS
+              C compiler flags for GLIB28, overriding pkg-config
+  GLIB28_LIBS linker flags for GLIB28, overriding pkg-config
   JSON_GLIB_CFLAGS
               C compiler flags for JSON_GLIB, overriding pkg-config
   JSON_GLIB_LIBS
@@ -2753,6 +2761,7 @@ have_x12a="yes"
 have_audio="no"
 have_sourceview="no"
 fake_gtkspinner="yes"
+fake_mono_time="no"
 have_gnu_regex="no"
 have_libxml2="no"
 have_xslt="no"
@@ -17338,15 +17347,14 @@ fi
 fi
 if test "$PKG_CONFIG" = "no" ; then
    echo "
-   Please install pkg-config and then reconfigure gretl.
-   pkg-config is available from http://www.freedesktop.org/
-   "
+Please install pkg-config and then reconfigure gretl.
+pkg-config is available from http://www.freedesktop.org/
+"
    exit 1
 fi
 
 orig_CFLAGS=$CFLAGS
 
-if test "$PKG_CONFIG" != "no" ; then
 
 
 
@@ -17538,12 +17546,11 @@ else
 $as_echo "yes" >&6; }
 	have_fftw3="yes"
 fi
-fi
 
 if test "$use_curl" = "yes" ; then
   if test "x$CURL_CFLAGS" != "x" || test "x$CURL_LIBS" != "x" ; then
     have_curl="yes"
-  elif test "$PKG_CONFIG" != "no" ; then
+  else
 
 pkg_failed=no
 { $as_echo "$as_me:${as_lineno-$LINENO}: checking for CURL" >&5
@@ -17622,7 +17629,6 @@ fi
   fi
 fi
 
-if test "$PKG_CONFIG" != "no" ; then
 
 pkg_failed=no
 { $as_echo "$as_me:${as_lineno-$LINENO}: checking for GLIB" >&5
@@ -17694,10 +17700,179 @@ else
 $as_echo "yes" >&6; }
 	have_glib2="yes"
 fi
+if test "${have_glib2}" = "no" ; then
+   echo "
+Please install glib-2.0 >= 2.14.0 and then reconfigure gretl.
+glib-2.0 is available from http://www.gtk.org/
+"
+   exit 1
+fi
+
+if test "$darwin_build" = "no" ; then
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for GLIB28" >&5
+$as_echo_n "checking for GLIB28... " >&6; }
+
+if test -n "$GLIB28_CFLAGS"; then
+    pkg_cv_GLIB28_CFLAGS="$GLIB28_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"glib-2.0 >= 2.28.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "glib-2.0 >= 2.28.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_GLIB28_CFLAGS=`$PKG_CONFIG --cflags "glib-2.0 >= 2.28.0" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$GLIB28_LIBS"; then
+    pkg_cv_GLIB28_LIBS="$GLIB28_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"glib-2.0 >= 2.28.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "glib-2.0 >= 2.28.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_GLIB28_LIBS=`$PKG_CONFIG --libs "glib-2.0 >= 2.28.0" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+   	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        GLIB28_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "glib-2.0 >= 2.28.0" 2>&1`
+        else
+	        GLIB28_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "glib-2.0 >= 2.28.0" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$GLIB28_PKG_ERRORS" >&5
+
+	fake_mono_time="yes"
+elif test $pkg_failed = untried; then
+     	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+	fake_mono_time="yes"
+else
+	GLIB28_CFLAGS=$pkg_cv_GLIB28_CFLAGS
+	GLIB28_LIBS=$pkg_cv_GLIB28_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	fake_mono_time="no"
+fi
+fi
+if test "$fake_mono_time" = "yes" ; then
+   have_clock_gettime="no"
+   { $as_echo "$as_me:${as_lineno-$LINENO}: checking for clock_gettime in -lc" >&5
+$as_echo_n "checking for clock_gettime in -lc... " >&6; }
+if ${ac_cv_lib_c_clock_gettime+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lc  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char clock_gettime ();
+int
+main ()
+{
+return clock_gettime ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  ac_cv_lib_c_clock_gettime=yes
+else
+  ac_cv_lib_c_clock_gettime=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_c_clock_gettime" >&5
+$as_echo "$ac_cv_lib_c_clock_gettime" >&6; }
+if test "x$ac_cv_lib_c_clock_gettime" = xyes; then :
+  have_clock_gettime="yes"
+fi
+
+   if test "$have_clock_gettime" = "no" ; then
+      { $as_echo "$as_me:${as_lineno-$LINENO}: checking for clock_gettime in -lrt" >&5
+$as_echo_n "checking for clock_gettime in -lrt... " >&6; }
+if ${ac_cv_lib_rt_clock_gettime+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lrt  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char clock_gettime ();
+int
+main ()
+{
+return clock_gettime ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  ac_cv_lib_rt_clock_gettime=yes
+else
+  ac_cv_lib_rt_clock_gettime=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_rt_clock_gettime" >&5
+$as_echo "$ac_cv_lib_rt_clock_gettime" >&6; }
+if test "x$ac_cv_lib_rt_clock_gettime" = xyes; then :
+  have_clock_gettime="yes"; \
+       RT_LIB="-lrt" ;
+fi
+
+   fi
+   if test "$have_clock_gettime" = "yes" ; then
+      $as_echo "#define HAVE_CLOCK_GETTIME 1" >>confdefs.h
+
+   fi
 fi
 
 if test "$try_json_glib" = "yes" ; then
-   if test "$PKG_CONFIG" != "no" ; then
 
 pkg_failed=no
 { $as_echo "$as_me:${as_lineno-$LINENO}: checking for JSON_GLIB" >&5
@@ -17769,7 +17944,6 @@ else
 $as_echo "yes" >&6; }
 	have_json_glib="yes"
 fi
-   fi
    if test $have_json_glib = "no" ; then
 echo "
 The json-glib-1.0 library was not found, or the version found
@@ -23642,7 +23816,7 @@ libcurl is available from http://curl.haxx.se/libcurl/
 
 elif test "${have_glib2}" = "no" ; then
 echo "
-Please install glib-2.0 >= 2.12.0 and then reconfigure gretl.
+Please install glib-2.0 >= 2.14.0 and then reconfigure gretl.
 glib-2.0 is available from http://www.gtk.org/
 "
 
