update lapack autoconf to allow for gcc 4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24148,9 +24148,80 @@ fi;
   lapack_config_args="$lapack_config_args --prefix=$lapack_config_prefix"
 
   if test x"${LAPACK_LIBS}" = x ; then
-     echo "$as_me:$LINENO: checking for libg2c or libf2c" >&5
-echo $ECHO_N "checking for libg2c or libf2c... $ECHO_C" >&6
-     echo "$as_me:$LINENO: checking for c_sqrt in -lg2c" >&5
+     echo "$as_me:$LINENO: checking for libgfortran" >&5
+echo $ECHO_N "checking for libgfortran... $ECHO_C" >&6
+     echo "$as_me:$LINENO: checking for etime_ in -lgfortran" >&5
+echo $ECHO_N "checking for etime_ in -lgfortran... $ECHO_C" >&6
+if test "${ac_cv_lib_gfortran_etime_+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgfortran  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char etime_ ();
+int
+main ()
+{
+etime_ ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_gfortran_etime_=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_gfortran_etime_=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_gfortran_etime_" >&5
+echo "${ECHO_T}$ac_cv_lib_gfortran_etime_" >&6
+if test $ac_cv_lib_gfortran_etime_ = yes; then
+  FLIB="-lgfortran"
+else
+  FLIB="none"
+fi
+
+     if test $FLIB = "none" ; then
+        echo "$as_me:$LINENO: checking for c_sqrt in -lg2c" >&5
 echo $ECHO_N "checking for c_sqrt in -lg2c... $ECHO_C" >&6
 if test "${ac_cv_lib_g2c_c_sqrt+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -24220,6 +24291,7 @@ else
   FLIB="none"
 fi
 
+     fi
      if test $FLIB = "none" ; then
         echo "$as_me:$LINENO: checking for c_sqrt in -lf2c" >&5
 echo $ECHO_N "checking for c_sqrt in -lf2c... $ECHO_C" >&6
@@ -24293,7 +24365,7 @@ fi
 
      fi
      if test $FLIB = "none" ; then
-        echo "*** Couldn't find either libg2c or libf2c"
+        echo "*** Couldn't find ligfortran, libg2c or libf2c"
      fi
   fi
 
