add Jack's arma patch; small ratsdata mods

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -25179,23 +25179,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for libxml-2.0" >&5
-echo $ECHO_N "checking for libxml-2.0... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for libxml-2.0 >= 2.5.0" >&5
+echo $ECHO_N "checking for libxml-2.0 >= 2.5.0... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "libxml-2.0" ; then
+        if $PKG_CONFIG --exists "libxml-2.0 >= 2.5.0" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking XML_CFLAGS" >&5
 echo $ECHO_N "checking XML_CFLAGS... $ECHO_C" >&6
-            XML_CFLAGS=`$PKG_CONFIG --cflags "libxml-2.0"`
+            XML_CFLAGS=`$PKG_CONFIG --cflags "libxml-2.0 >= 2.5.0"`
             echo "$as_me:$LINENO: result: $XML_CFLAGS" >&5
 echo "${ECHO_T}$XML_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking XML_LIBS" >&5
 echo $ECHO_N "checking XML_LIBS... $ECHO_C" >&6
-            XML_LIBS=`$PKG_CONFIG --libs "libxml-2.0"`
+            XML_LIBS=`$PKG_CONFIG --libs "libxml-2.0 >= 2.5.0"`
             echo "$as_me:$LINENO: result: $XML_LIBS" >&5
 echo "${ECHO_T}$XML_LIBS" >&6
         else
@@ -25203,7 +25203,7 @@ echo "${ECHO_T}$XML_LIBS" >&6
             XML_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            XML_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxml-2.0"`
+            XML_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxml-2.0 >= 2.5.0"`
             echo $XML_PKG_ERRORS
         fi
 
@@ -25218,8 +25218,8 @@ echo "${ECHO_T}$XML_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (libxml-2.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (libxml-2.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (libxml-2.0 >= 2.5.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (libxml-2.0 >= 2.5.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
@@ -25364,50 +25364,109 @@ _ACEOF
 fi
 
 if test x"${XML_LIBS}" = x ; then
-  XMLCONF=''
-  if test "$prefer_xml1" = "yes" ; then
-    for ac_prog in xml-config xml2-config
-do
-  # Extract the first word of "$ac_prog", so it can be a program name with args.
-set dummy $ac_prog; ac_word=$2
+  if test "$have_gtk" = "2.0" ; then
+
+  succeeded=no
+
+  if test -z "$PKG_CONFIG"; then
+    # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_prog_XMLCONF+set}" = set; then
+if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  if test -n "$XMLCONF"; then
-  ac_cv_prog_XMLCONF="$XMLCONF" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
 for as_dir in $PATH
 do
   IFS=$as_save_IFS
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_XMLCONF="$ac_prog"
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
 done
 done
 
+  test -z "$ac_cv_path_PKG_CONFIG" && ac_cv_path_PKG_CONFIG="no"
+  ;;
+esac
 fi
-fi
-XMLCONF=$ac_cv_prog_XMLCONF
-if test -n "$XMLCONF"; then
-  echo "$as_me:$LINENO: result: $XMLCONF" >&5
-echo "${ECHO_T}$XMLCONF" >&6
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+
+if test -n "$PKG_CONFIG"; then
+  echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
+echo "${ECHO_T}$PKG_CONFIG" >&6
 else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
-  test -n "$XMLCONF" && break
-done
+  fi
+
+  if test "$PKG_CONFIG" = "no" ; then
+     echo "*** The pkg-config script could not be found. Make sure it is"
+     echo "*** in your path, or set the PKG_CONFIG environment variable"
+     echo "*** to the full path to pkg-config."
+     echo "*** Or see http://www.freedesktop.org/software/pkgconfig to get pkg-config."
+  else
+     PKG_CONFIG_MIN_VERSION=0.9.0
+     if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
+        echo "$as_me:$LINENO: checking for libxml-2.0 >= 2.5.0" >&5
+echo $ECHO_N "checking for libxml-2.0 >= 2.5.0... $ECHO_C" >&6
+
+        if $PKG_CONFIG --exists "libxml-2.0 >= 2.5.0" ; then
+            echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+            succeeded=yes
+
+            echo "$as_me:$LINENO: checking XML_CFLAGS" >&5
+echo $ECHO_N "checking XML_CFLAGS... $ECHO_C" >&6
+            XML_CFLAGS=`$PKG_CONFIG --cflags "libxml-2.0 >= 2.5.0"`
+            echo "$as_me:$LINENO: result: $XML_CFLAGS" >&5
+echo "${ECHO_T}$XML_CFLAGS" >&6
+
+            echo "$as_me:$LINENO: checking XML_LIBS" >&5
+echo $ECHO_N "checking XML_LIBS... $ECHO_C" >&6
+            XML_LIBS=`$PKG_CONFIG --libs "libxml-2.0 >= 2.5.0"`
+            echo "$as_me:$LINENO: result: $XML_LIBS" >&5
+echo "${ECHO_T}$XML_LIBS" >&6
+        else
+            XML_CFLAGS=""
+            XML_LIBS=""
+            ## If we have a custom action on failure, don't print errors, but
+            ## do set a variable so people can do so.
+            XML_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxml-2.0 >= 2.5.0"`
+            echo $XML_PKG_ERRORS
+        fi
+
+
+
+     else
+        echo "*** Your version of pkg-config is too old. You need version $PKG_CONFIG_MIN_VERSION or newer."
+        echo "*** See http://www.freedesktop.org/software/pkgconfig"
+     fi
+  fi
+
+  if test $succeeded = yes; then
+     :
+  else
+     { { echo "$as_me:$LINENO: error: Library requirements (libxml-2.0 >= 2.5.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (libxml-2.0 >= 2.5.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
 
   else
-    for ac_prog in xml2-config xml-config
+    XMLCONF=''
+    if test "$prefer_xml1" = "yes" ; then
+      for ac_prog in xml-config xml2-config
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -25447,13 +25506,55 @@ fi
   test -n "$XMLCONF" && break
 done
 
+    else
+      for ac_prog in xml2-config xml-config
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_XMLCONF+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$XMLCONF"; then
+  ac_cv_prog_XMLCONF="$XMLCONF" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_XMLCONF="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
   fi
+done
+done
 
-  if test x"${XMLCONF}" != x ; then
-    XML_CFLAGS=`$XMLCONF --cflags`
-    XML_LIBS=`$XMLCONF --libs`
+fi
+fi
+XMLCONF=$ac_cv_prog_XMLCONF
+if test -n "$XMLCONF"; then
+  echo "$as_me:$LINENO: result: $XMLCONF" >&5
+echo "${ECHO_T}$XMLCONF" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$XMLCONF" && break
+done
+
+    fi
+    if test x"${XMLCONF}" != x ; then
+      XML_CFLAGS=`$XMLCONF --cflags`
+      XML_LIBS=`$XMLCONF --libs`
+    fi
   fi
 fi
+
 
 
 
