quantreg: fix tau sequence graph for non-'.' locales

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -917,10 +917,13 @@ GTK_CFLAGS
 GTK_LIBS
 GTKPRINT_CFLAGS
 GTKPRINT_LIBS
+GTKSOURCEVIEW_CFLAGS
+GTKSOURCEVIEW_LIBS
 build_gui
 have_gtk
 have_gmp
 have_mpfr
+have_sourceview
 have_gnu_regex
 have_audio
 have_odbc
@@ -957,6 +960,7 @@ with_gnome
 with_gnome_install
 with_gmp
 with_mpfr
+with_gtksourceview
 with_x_12_arima
 with_tramo_seats
 with_audio
@@ -991,6 +995,8 @@ GTK_CFLAGS
 GTK_LIBS
 GTKPRINT_CFLAGS
 GTKPRINT_LIBS
+GTKSOURCEVIEW_CFLAGS
+GTKSOURCEVIEW_LIBS
 GDK_PIXBUF_CFLAGS
 GDK_PIXBUF_LIBS
 GNOME_CFLAGS
@@ -1647,10 +1653,11 @@ Optional Packages:
   --with-gnome-install=DIR  where to install gnome-specific files [default=auto]
   --with-gmp            Use Gnu Multiple Precision library [default=auto]
   --with-mpfr            Use MPFR library [default=auto]
-  --with-x-12-arima     include X-12-ARIMA support [default=yes]
-  --with-tramo-seats    include TRAMO/SEATS support [default=yes]
-  --with-audio    include audio graph support (experimental)
-  --with-odbc    include ODBC support (experimental)
+  --with-gtksourceview   Use installed gtksourceview [default=auto]
+  --with-x-12-arima      include X-12-ARIMA support [default=yes]
+  --with-tramo-seats     include TRAMO/SEATS support [default=yes]
+  --with-audio           include audio graph support (experimental)
+  --with-odbc            include ODBC support (experimental)
   --with-pic              try to use only PIC/non-PIC objects [default=use
                           both]
   --with-gnu-ld           assume the C compiler uses GNU ld [default=no]
@@ -1681,6 +1688,10 @@ Some influential environment variables:
               C compiler flags for GTKPRINT, overriding pkg-config
   GTKPRINT_LIBS
               linker flags for GTKPRINT, overriding pkg-config
+  GTKSOURCEVIEW_CFLAGS
+              C compiler flags for GTKSOURCEVIEW, overriding pkg-config
+  GTKSOURCEVIEW_LIBS
+              linker flags for GTKSOURCEVIEW, overriding pkg-config
   GDK_PIXBUF_CFLAGS
               C compiler flags for GDK_PIXBUF, overriding pkg-config
   GDK_PIXBUF_LIBS
@@ -2215,6 +2226,9 @@ seek_inet_addr="no"
 have_tramo="yes"
 have_x12a="yes"
 have_audio="no"
+try_sourceview="yes"
+have_sourceview="no"
+bundled_sourceview="yes"
 have_gnu_regex="no"
 have_libxml2="no"
 have_xslt="no"
@@ -6460,6 +6474,20 @@ fi
 
 
 
+# Check whether --with-gtksourceview was given.
+if test "${with_gtksourceview+set}" = set; then
+  withval=$with_gtksourceview; if test "x${withval}" = "xno"
+then
+  try_sourceview=no
+else
+  try_sourceview=yes
+fi
+else
+  try_sourceview=yes
+fi
+
+
+
 # Check whether --with-x-12-arima was given.
 if test "${with_x_12_arima+set}" = set; then
   withval=$with_x_12_arima; if test "$withval" = "no"
@@ -7847,13 +7875,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:7850: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:7878: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:7853: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:7881: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:7856: output\"" >&5)
+  (eval echo "\"\$as_me:7884: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -8961,7 +8989,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 8964 "configure"' > conftest.$ac_ext
+  echo '#line 8992 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -10010,11 +10038,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10013: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10041: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10017: \$? = $ac_status" >&5
+   echo "$as_me:10045: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -10334,11 +10362,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10337: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10365: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10341: \$? = $ac_status" >&5
+   echo "$as_me:10369: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -10439,11 +10467,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10442: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10470: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10446: \$? = $ac_status" >&5
+   echo "$as_me:10474: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10494,11 +10522,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10497: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10525: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10501: \$? = $ac_status" >&5
+   echo "$as_me:10529: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13286,7 +13314,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 13289 "configure"
+#line 13317 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13386,7 +13414,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 13389 "configure"
+#line 13417 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18218,7 +18246,160 @@ $as_echo "yes" >&6; }
 fi
 fi
 
-if test "$have_gtk" = "2.0" ; then
+if test "$have_gtk" = "2.0" && test "$try_sourceview" = "yes" ; then
+
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for GTKSOURCEVIEW" >&5
+$as_echo_n "checking for GTKSOURCEVIEW... " >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$GTKSOURCEVIEW_CFLAGS"; then
+        pkg_cv_GTKSOURCEVIEW_CFLAGS="$GTKSOURCEVIEW_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gtksourceview-2.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "gtksourceview-2.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_GTKSOURCEVIEW_CFLAGS=`$PKG_CONFIG --cflags "gtksourceview-2.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$GTKSOURCEVIEW_LIBS"; then
+        pkg_cv_GTKSOURCEVIEW_LIBS="$GTKSOURCEVIEW_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gtksourceview-2.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "gtksourceview-2.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_GTKSOURCEVIEW_LIBS=`$PKG_CONFIG --libs "gtksourceview-2.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        GTKSOURCEVIEW_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "gtksourceview-2.0"`
+        else
+	        GTKSOURCEVIEW_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "gtksourceview-2.0"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$GTKSOURCEVIEW_PKG_ERRORS" >&5
+
+	echo "version 2.0 not found"
+
+elif test $pkg_failed = untried; then
+	echo "version 2.0 not found"
+
+else
+	GTKSOURCEVIEW_CFLAGS=$pkg_cv_GTKSOURCEVIEW_CFLAGS
+	GTKSOURCEVIEW_LIBS=$pkg_cv_GTKSOURCEVIEW_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+	cat >>confdefs.h <<\_ACEOF
+#define USE_GTKSOURCEVIEW_2 1
+_ACEOF
+
+      have_sourceview="2.0"
+fi
+    if test "$have_sourceview" != "2.0" ; then
+
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for GTKSOURCEVIEW" >&5
+$as_echo_n "checking for GTKSOURCEVIEW... " >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$GTKSOURCEVIEW_CFLAGS"; then
+        pkg_cv_GTKSOURCEVIEW_CFLAGS="$GTKSOURCEVIEW_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gtksourceview-1.0 >= 1.8.5\"") >&5
+  ($PKG_CONFIG --exists --print-errors "gtksourceview-1.0 >= 1.8.5") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_GTKSOURCEVIEW_CFLAGS=`$PKG_CONFIG --cflags "gtksourceview-1.0 >= 1.8.5" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$GTKSOURCEVIEW_LIBS"; then
+        pkg_cv_GTKSOURCEVIEW_LIBS="$GTKSOURCEVIEW_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gtksourceview-1.0 >= 1.8.5\"") >&5
+  ($PKG_CONFIG --exists --print-errors "gtksourceview-1.0 >= 1.8.5") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_GTKSOURCEVIEW_LIBS=`$PKG_CONFIG --libs "gtksourceview-1.0 >= 1.8.5" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        GTKSOURCEVIEW_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "gtksourceview-1.0 >= 1.8.5"`
+        else
+	        GTKSOURCEVIEW_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "gtksourceview-1.0 >= 1.8.5"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$GTKSOURCEVIEW_PKG_ERRORS" >&5
+
+	echo "will use 1.8.5"
+         bundled_sourceview="yes"
+
+elif test $pkg_failed = untried; then
+	echo "will use 1.8.5"
+         bundled_sourceview="yes"
+
+else
+	GTKSOURCEVIEW_CFLAGS=$pkg_cv_GTKSOURCEVIEW_CFLAGS
+	GTKSOURCEVIEW_LIBS=$pkg_cv_GTKSOURCEVIEW_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+	have_sourceview="1.0"
+fi
+    fi
+fi
+
+if test "$bundled_sourceview" = "yes" ; then
 
 
 
@@ -18331,6 +18512,7 @@ if test x"${MSGFMT}" != x ; then
 else
    echo "*** msgfmt not found, can't build message catalogs"
 fi
+
 
 
 
