fix for a build using GTK < 2.8.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -625,7 +625,7 @@ build_mailer
 have_odbc
 have_audio
 have_gnu_regex
-have_gtkspinner
+fake_gtkspinner
 have_sourceview
 have_mpfr
 have_gmp
@@ -633,10 +633,12 @@ have_gtk
 build_gui
 GTKSOURCEVIEW_LIBS
 GTKSOURCEVIEW_CFLAGS
-GTKSPINNER_LIBS
-GTKSPINNER_CFLAGS
+GTKCAIRO_LIBS
+GTKCAIRO_CFLAGS
 GTKPRINT_LIBS
 GTKPRINT_CFLAGS
+GTKSPINNER_LIBS
+GTKSPINNER_CFLAGS
 GTK_LIBS
 GTK_CFLAGS
 GLIB_LIBS
@@ -833,10 +835,12 @@ GLIB_CFLAGS
 GLIB_LIBS
 GTK_CFLAGS
 GTK_LIBS
-GTKPRINT_CFLAGS
-GTKPRINT_LIBS
 GTKSPINNER_CFLAGS
 GTKSPINNER_LIBS
+GTKPRINT_CFLAGS
+GTKPRINT_LIBS
+GTKCAIRO_CFLAGS
+GTKCAIRO_LIBS
 GTKSOURCEVIEW_CFLAGS
 GTKSOURCEVIEW_LIBS
 GDK_PIXBUF_CFLAGS
@@ -1524,14 +1528,18 @@ Some influential environment variables:
   GLIB_LIBS   linker flags for GLIB, overriding pkg-config
   GTK_CFLAGS  C compiler flags for GTK, overriding pkg-config
   GTK_LIBS    linker flags for GTK, overriding pkg-config
-  GTKPRINT_CFLAGS
-              C compiler flags for GTKPRINT, overriding pkg-config
-  GTKPRINT_LIBS
-              linker flags for GTKPRINT, overriding pkg-config
   GTKSPINNER_CFLAGS
               C compiler flags for GTKSPINNER, overriding pkg-config
   GTKSPINNER_LIBS
               linker flags for GTKSPINNER, overriding pkg-config
+  GTKPRINT_CFLAGS
+              C compiler flags for GTKPRINT, overriding pkg-config
+  GTKPRINT_LIBS
+              linker flags for GTKPRINT, overriding pkg-config
+  GTKCAIRO_CFLAGS
+              C compiler flags for GTKCAIRO, overriding pkg-config
+  GTKCAIRO_LIBS
+              linker flags for GTKCAIRO, overriding pkg-config
   GTKSOURCEVIEW_CFLAGS
               C compiler flags for GTKSOURCEVIEW, overriding pkg-config
   GTKSOURCEVIEW_LIBS
@@ -2628,7 +2636,6 @@ new_readline="no"
 have_zlib="no"
 have_gtk="no"
 have_gtkprint="no"
-have_gtkspinner="no"
 have_gnome="no"
 have_gmp="no"
 have_mpfr="no"
@@ -2641,6 +2648,7 @@ have_audio="no"
 try_sourceview="yes"
 have_sourceview="no"
 bundled_sourceview="yes"
+fake_gtkspinner="yes"
 have_gnu_regex="no"
 have_libxml2="no"
 have_xslt="no"
@@ -16275,6 +16283,77 @@ fi
 if test "$have_gtk" = "2.0" ; then
 
 pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for GTKSPINNER" >&5
+$as_echo_n "checking for GTKSPINNER... " >&6; }
+
+if test -n "$GTKSPINNER_CFLAGS"; then
+    pkg_cv_GTKSPINNER_CFLAGS="$GTKSPINNER_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 >= 2.20.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 >= 2.20.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_GTKSPINNER_CFLAGS=`$PKG_CONFIG --cflags "gtk+-2.0 >= 2.20.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$GTKSPINNER_LIBS"; then
+    pkg_cv_GTKSPINNER_LIBS="$GTKSPINNER_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 >= 2.20.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 >= 2.20.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_GTKSPINNER_LIBS=`$PKG_CONFIG --libs "gtk+-2.0 >= 2.20.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        GTKSPINNER_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "gtk+-2.0 >= 2.20.0" 2>&1`
+        else
+	        GTKSPINNER_PKG_ERRORS=`$PKG_CONFIG --print-errors "gtk+-2.0 >= 2.20.0" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$GTKSPINNER_PKG_ERRORS" >&5
+
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+                fake_gtkspinner="yes"
+elif test $pkg_failed = untried; then
+	fake_gtkspinner="yes"
+else
+	GTKSPINNER_CFLAGS=$pkg_cv_GTKSPINNER_CFLAGS
+	GTKSPINNER_LIBS=$pkg_cv_GTKSPINNER_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	have_gtkprint="yes"
+      fake_gtkspinner="no"
+fi
+fi
+
+if test "$have_gtk" = "2.0" && test "$have_gtkprint" = "no" ; then
+
+pkg_failed=no
 { $as_echo "$as_me:${as_lineno-$LINENO}: checking for GTKPRINT" >&5
 $as_echo_n "checking for GTKPRINT... " >&6; }
 
@@ -16344,38 +16423,38 @@ $as_echo "yes" >&6; }
 fi
 fi
 
-if test "$have_gtk" = "2.0" ; then
+if test "$have_gtk" = "2.0" && test "$have_gtkprint" = "no" ; then
 
 pkg_failed=no
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for GTKSPINNER" >&5
-$as_echo_n "checking for GTKSPINNER... " >&6; }
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for GTKCAIRO" >&5
+$as_echo_n "checking for GTKCAIRO... " >&6; }
 
-if test -n "$GTKSPINNER_CFLAGS"; then
-    pkg_cv_GTKSPINNER_CFLAGS="$GTKSPINNER_CFLAGS"
+if test -n "$GTKCAIRO_CFLAGS"; then
+    pkg_cv_GTKCAIRO_CFLAGS="$GTKCAIRO_CFLAGS"
  elif test -n "$PKG_CONFIG"; then
     if test -n "$PKG_CONFIG" && \
-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 >= 2.20.0\""; } >&5
-  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 >= 2.20.0") 2>&5
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 >= 2.8.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 >= 2.8.0") 2>&5
   ac_status=$?
   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
   test $ac_status = 0; }; then
-  pkg_cv_GTKSPINNER_CFLAGS=`$PKG_CONFIG --cflags "gtk+-2.0 >= 2.20.0" 2>/dev/null`
+  pkg_cv_GTKCAIRO_CFLAGS=`$PKG_CONFIG --cflags "gtk+-2.0 >= 2.8.0" 2>/dev/null`
 else
   pkg_failed=yes
 fi
  else
     pkg_failed=untried
 fi
-if test -n "$GTKSPINNER_LIBS"; then
-    pkg_cv_GTKSPINNER_LIBS="$GTKSPINNER_LIBS"
+if test -n "$GTKCAIRO_LIBS"; then
+    pkg_cv_GTKCAIRO_LIBS="$GTKCAIRO_LIBS"
  elif test -n "$PKG_CONFIG"; then
     if test -n "$PKG_CONFIG" && \
-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 >= 2.20.0\""; } >&5
-  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 >= 2.20.0") 2>&5
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk+-2.0 >= 2.8.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "gtk+-2.0 >= 2.8.0") 2>&5
   ac_status=$?
   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
   test $ac_status = 0; }; then
-  pkg_cv_GTKSPINNER_LIBS=`$PKG_CONFIG --libs "gtk+-2.0 >= 2.20.0" 2>/dev/null`
+  pkg_cv_GTKCAIRO_LIBS=`$PKG_CONFIG --libs "gtk+-2.0 >= 2.8.0" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -16393,26 +16472,26 @@ else
         _pkg_short_errors_supported=no
 fi
         if test $_pkg_short_errors_supported = yes; then
-	        GTKSPINNER_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "gtk+-2.0 >= 2.20.0" 2>&1`
+	        GTKCAIRO_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "gtk+-2.0 >= 2.8.0" 2>&1`
         else
-	        GTKSPINNER_PKG_ERRORS=`$PKG_CONFIG --print-errors "gtk+-2.0 >= 2.20.0" 2>&1`
+	        GTKCAIRO_PKG_ERRORS=`$PKG_CONFIG --print-errors "gtk+-2.0 >= 2.8.0" 2>&1`
         fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$GTKSPINNER_PKG_ERRORS" >&5
+	echo "$GTKCAIRO_PKG_ERRORS" >&5
 
 	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
 $as_echo "no" >&6; }
-                have_gtkspinner="no"
+                fake_gtkspinner="no"
 
 elif test $pkg_failed = untried; then
-	have_gtkspinner="no"
+	fake_gtkspinner="no"
 
 else
-	GTKSPINNER_CFLAGS=$pkg_cv_GTKSPINNER_CFLAGS
-	GTKSPINNER_LIBS=$pkg_cv_GTKSPINNER_LIBS
+	GTKCAIRO_CFLAGS=$pkg_cv_GTKCAIRO_CFLAGS
+	GTKCAIRO_LIBS=$pkg_cv_GTKCAIRO_LIBS
         { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
 $as_echo "yes" >&6; }
-	have_gtkspinner="yes"
+	fake_gtkspinner="yes"
 fi
 fi
 
